# resolver: nightly-2025-09-11 # ghc-9.12.2
resolver: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/43.yaml # GHC 9.6.6
system-ghc: true

packages:
- .

extra-deps: []

flags: {}

extra-package-dbs: []
